services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fct-test-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: fct-test-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: fct_test_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: fct_test
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: fct-test-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
