services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fct-test-app
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: fct-test-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
